### ISSUE TITLE
Navbar buttons do not trigger hover/clickable cursor, contrast between normal/hovered is too light

### ISSUE THREAD

**Issue by LucyLetour** [RUCOGS/rucogs.github.io#2]
When hovering over navbar items ("home", "calendar", etc.) the cursor remains as the arrow. This makes it hard to tell if the button is being hovered. Also, the contrast between hovered and not should be greater to aid in this visual distinction.

- [x] Change cursor when hovering over navbar buttons
- [x] Make text hover color have greater contrast with normal color

**Comment by Atlinx** [comment]
Closed with merged PR. We cannot lower the brightness of the nav bar text hover color anymore because it would then blend into the red background (They share similar grayscale values). The only other option is making it black, which I don't find appealing.
