### ISSUE TITLE
Add Discord / Social Media links to the navbar

### ISSUE THREAD

**Issue by Sorrer** [RUCOGS/rucogs.github.io#9]
Inorder to increase traffic to the most important areas of our club we should add buttons for discord, email listing, and maybe social media. Discord and email listing should prioritize the navbar. Social media can be linked in an about us or in some content panel.

- [ ] Add Discord invite button to the navbar
- [ ] Add Email signup button to the navbar
- [ ] Find and add social media links to somewhere on the site

**Comment by Atlinx** [comment]
The other social media links will be put in the footer.
